### ISSUE TITLE
Feature to actually setup imap and smtp to send emails through a custom domain.

### ISSUE THREAD

**Issue by XolifyDev** [leerob/next-email-client#8]
Hey! This isn’t an issue but I wanted to see if you were gonna add a way to do this or if someone else was going to.

Add a way to setup your account with a domain and be able to send and receive emails.

**Comment by leerob** [comment]
Not planning to do this, but I love the idea for a fork 😄

**Comment by troubleshootme** [comment]
@leerob to replicate a client such as Superhuman, one would need to use Google and MS API's for the email functionality, correct?
